# Generated by Django 3.2.13 on 2022-05-17 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('C', 'Car'), ('M', 'Motorcycle'), ('B', 'Bicycle')], max_length=1)),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('color', models.CharField(max_length=10)),
                ('engine', models.CharField(blank=True, choices=[('c', 'Combustion'), ('e', 'Electric')], max_length=1, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
