# Generated by Django 3.2.13 on 2022-05-17 17:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False 

    dependencies = [
        ('place', '0002_rename_place_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='place',
            new_name='parking',
        ),
    ]
