# Generated by Django 3.2.13 on 2022-05-17 17:11

from django.db import migrations


class Migration(migrations.Migration):
    
    atomic = False 

    dependencies = [
        ('place', '0003_rename_place_rack_parking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parking',
            new_name='Place',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='parking',
            new_name='place',
        ),
    ]
