# Generated by Django 3.2.13 on 2022-05-17 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20220517_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='statu',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2e6fb309-d791-45bb-ad7d-9b59bcab39f7')),
        ),
    ]
