# Generated by Django 3.2.13 on 2022-05-17 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20220517_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('306f9620-d356-44ff-8468-686b3e20c73a')),
        ),
    ]
