# Generated by Django 3.2 on 2022-05-17 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20220517_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a56b6d00-fcb0-4a0c-ae88-5739108137f7')),
        ),
    ]
