# Generated by Django 3.2 on 2022-05-18 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0009_auto_20220518_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6b1d6412-2718-4c3e-a62d-65c383e445b7')),
        ),
    ]
