# Generated by Django 3.2 on 2022-05-18 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0efe5927-70da-4c14-bfe8-0cf34d80c197')),
        ),
    ]
