# Generated by Django 3.2 on 2022-05-18 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_auto_20220518_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f9060ec0-7c5d-49df-a063-e6889cd5b2dc')),
        ),
    ]
