# Generated by Django 3.2 on 2022-05-18 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_auto_20220518_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('57eb1400-d056-401c-b9ed-8cd721fd4de4')),
        ),
    ]
