# Generated by Django 3.2 on 2022-05-18 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a7c626ea-df28-4baf-9d24-c0bd8d94332f')),
        ),
    ]
