# Generated by Django 3.2.13 on 2022-05-19 18:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_alter_rack_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3d09369b-6b3c-440d-9031-0dd6a973239a')),
        ),
    ]
